[package]
name = "am-vcv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annembed = "0.1.1"
cxx = "1.0.116"
nalgebra = "0.32.3"
